### ISSUE TITLE
Installation Guide, options

### ISSUE THREAD

**Issue by kravemir** [S0lll0s/i3bgbar#9]
Hello,

I like this project. However, there's almost no documentation on installation.

How do I change installation folder? (I don't wanna replace existing i3bar)

**Comment by S0lll0s** [comment]
Just copy it by Hand.

I however do no longer recommend using i3bgbar, I will not update it with i3 updates so it might break completely ans time and it also has proven to be unstable.

Instead I now endorse using [BAR](/LemonBoy/bar) and the corresponding i3 bindings I built. Just check out the [powerline](/powerline/powerline) repo, it has Bern merged but I dont think its in a stabile release yet.
Also I am working on retiring i3-py because I suspect it is cause for some instability, but I have yet to do that.

*PS: note that BAR doesn't work with i3's bar directive, just exec it in your conf.*
